// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: feat.proto

package pb

import (
	_ "github.com/onexstack/protobuf-go-plugins/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Plain carries rules and nothing else. It is the control: its exported
// Validate/ValidateAll must keep the names, and the shape, that PGV has always
// produced, so that a message the option is not applied to generates
// byte-identically to upstream.
type Plain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Plain) Reset() {
	*x = Plain{}
	mi := &file_feat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plain) ProtoMessage() {}

func (x *Plain) ProtoReflect() protoreflect.Message {
	mi := &file_feat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plain.ProtoReflect.Descriptor instead.
func (*Plain) Descriptor() ([]byte, []int) {
	return file_feat_proto_rawDescGZIP(), []int{0}
}

func (x *Plain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Custom opts out of the exported pair so a hand-written file can own it.
// Every rule below has to survive the rename: the in-list, the min_items and
// the generated error/lookup machinery are what the hand-written half calls
// into, and losing them would make the option useless.
type Custom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Ids           []string               `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Custom) Reset() {
	*x = Custom{}
	mi := &file_feat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Custom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Custom) ProtoMessage() {}

func (x *Custom) ProtoReflect() protoreflect.Message {
	mi := &file_feat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Custom.ProtoReflect.Descriptor instead.
func (*Custom) Descriptor() ([]byte, []int) {
	return file_feat_proto_rawDescGZIP(), []int{1}
}

func (x *Custom) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Custom) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// WithOneof covers the parts of the template that are not field rules: the
// oneof switch and the required-oneof check sit inside the same conditional
// block, so a oneof message is where a misplaced {{ end }} surfaces as a
// syntax error rather than as a silently missing rule.
type WithOneof struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Pick:
	//
	//	*WithOneof_A
	//	*WithOneof_B
	Pick          isWithOneof_Pick `protobuf_oneof:"pick"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithOneof) Reset() {
	*x = WithOneof{}
	mi := &file_feat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithOneof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithOneof) ProtoMessage() {}

func (x *WithOneof) ProtoReflect() protoreflect.Message {
	mi := &file_feat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithOneof.ProtoReflect.Descriptor instead.
func (*WithOneof) Descriptor() ([]byte, []int) {
	return file_feat_proto_rawDescGZIP(), []int{2}
}

func (x *WithOneof) GetPick() isWithOneof_Pick {
	if x != nil {
		return x.Pick
	}
	return nil
}

func (x *WithOneof) GetA() string {
	if x != nil {
		if x, ok := x.Pick.(*WithOneof_A); ok {
			return x.A
		}
	}
	return ""
}

func (x *WithOneof) GetB() string {
	if x != nil {
		if x, ok := x.Pick.(*WithOneof_B); ok {
			return x.B
		}
	}
	return ""
}

type isWithOneof_Pick interface {
	isWithOneof_Pick()
}

type WithOneof_A struct {
	A string `protobuf:"bytes,1,opt,name=a,proto3,oneof"`
}

type WithOneof_B struct {
	B string `protobuf:"bytes,2,opt,name=b,proto3,oneof"`
}

func (*WithOneof_A) isWithOneof_Pick() {}

func (*WithOneof_B) isWithOneof_Pick() {}

var File_feat_proto protoreflect.FileDescriptor

const file_feat_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"feat.proto\x12\x10validate.test.v1\x1a\x17validate/validate.proto\"$\n" +
	"\x05Plain\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\"N\n" +
	"\x06Custom\x12#\n" +
	"\x04code\x18\x01 \x01(\tB\x0f\xfaB\fr\n" +
	"\x10\x02R\x02aaR\x02bbR\x04code\x12\x1a\n" +
	"\x03ids\x18\x02 \x03(\tB\b\xfaB\x05\x92\x01\x02\b\x01R\x03ids:\x03\x88C\x01\"=\n" +
	"\tWithOneof\x12\x0e\n" +
	"\x01a\x18\x01 \x01(\tH\x00R\x01a\x12\x0e\n" +
	"\x01b\x18\x02 \x01(\tH\x00R\x01b:\x03\x88C\x01B\v\n" +
	"\x04pick\x12\x03\xf8B\x01BQZOgithub.com/onexstack/protobuf-go-plugins/cmd/protoc-gen-go-validate/tests/pb;pbb\x06proto3"

var (
	file_feat_proto_rawDescOnce sync.Once
	file_feat_proto_rawDescData []byte
)

func file_feat_proto_rawDescGZIP() []byte {
	file_feat_proto_rawDescOnce.Do(func() {
		file_feat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feat_proto_rawDesc), len(file_feat_proto_rawDesc)))
	})
	return file_feat_proto_rawDescData
}

var file_feat_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_feat_proto_goTypes = []any{
	(*Plain)(nil),     // 0: validate.test.v1.Plain
	(*Custom)(nil),    // 1: validate.test.v1.Custom
	(*WithOneof)(nil), // 2: validate.test.v1.WithOneof
}
var file_feat_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_feat_proto_init() }
func file_feat_proto_init() {
	if File_feat_proto != nil {
		return
	}
	file_feat_proto_msgTypes[2].OneofWrappers = []any{
		(*WithOneof_A)(nil),
		(*WithOneof_B)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feat_proto_rawDesc), len(file_feat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_feat_proto_goTypes,
		DependencyIndexes: file_feat_proto_depIdxs,
		MessageInfos:      file_feat_proto_msgTypes,
	}.Build()
	File_feat_proto = out.File
	file_feat_proto_goTypes = nil
	file_feat_proto_depIdxs = nil
}
