// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: feat.proto

package pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Plain with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Plain) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Plain with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in PlainMultiError, or nil if none found.
func (m *Plain) ValidateAll() error {
	return m.validate(true)
}

func (m *Plain) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := PlainValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return PlainMultiError(errors)
	}

	return nil
}

// PlainMultiError is an error wrapping multiple validation errors returned by
// Plain.ValidateAll() if the designated constraints aren't met.
type PlainMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PlainMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PlainMultiError) AllErrors() []error { return m }

// PlainValidationError is the validation error returned by Plain.Validate if
// the designated constraints aren't met.
type PlainValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PlainValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PlainValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PlainValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PlainValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PlainValidationError) ErrorName() string { return "PlainValidationError" }

// Error satisfies the builtin error interface
func (e PlainValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPlain.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PlainValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PlainValidationError{}

// _Validate runs the rules compiled from Custom and returns the first
// violation, or nil. It is the generated half of the pair; the exported
// Validate is hand-written and calls this.
func (m *Custom) _Validate() error {
	return m.validate(false)
}

// _ValidateAll runs the rules compiled from Custom and returns every violation
// wrapped in CustomMultiError, or nil if none found. It is the generated half
// of the pair; the exported ValidateAll is hand-written and calls this.
func (m *Custom) _ValidateAll() error {
	return m.validate(true)
}

func (m *Custom) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if _, ok := _Custom_Code_InLookup[m.GetCode()]; !ok {
		err := CustomValidationError{
			field:  "Code",
			reason: "value must be in list [aa bb]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetCode()) < 2 {
		err := CustomValidationError{
			field:  "Code",
			reason: "value length must be at least 2 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(m.GetIds()) < 1 {
		err := CustomValidationError{
			field:  "Ids",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CustomMultiError(errors)
	}

	return nil
}

// CustomMultiError is an error wrapping multiple validation errors returned by
// Custom.ValidateAll() if the designated constraints aren't met.
type CustomMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CustomMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CustomMultiError) AllErrors() []error { return m }

// CustomValidationError is the validation error returned by Custom.Validate if
// the designated constraints aren't met.
type CustomValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CustomValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CustomValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CustomValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CustomValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CustomValidationError) ErrorName() string { return "CustomValidationError" }

// Error satisfies the builtin error interface
func (e CustomValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCustom.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CustomValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CustomValidationError{}

var _Custom_Code_InLookup = map[string]struct{}{
	"aa": {},
	"bb": {},
}

// _Validate runs the rules compiled from WithOneof and returns the first
// violation, or nil. It is the generated half of the pair; the exported
// Validate is hand-written and calls this.
func (m *WithOneof) _Validate() error {
	return m.validate(false)
}

// _ValidateAll runs the rules compiled from WithOneof and returns every
// violation wrapped in WithOneofMultiError, or nil if none found. It is the
// generated half of the pair; the exported ValidateAll is hand-written and
// calls this.
func (m *WithOneof) _ValidateAll() error {
	return m.validate(true)
}

func (m *WithOneof) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	oneofPickPresent := false
	switch v := m.Pick.(type) {
	case *WithOneof_A:
		if v == nil {
			err := WithOneofValidationError{
				field:  "Pick",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofPickPresent = true
		// no validation rules for A
	case *WithOneof_B:
		if v == nil {
			err := WithOneofValidationError{
				field:  "Pick",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofPickPresent = true
		// no validation rules for B
	default:
		_ = v // ensures v is used
	}
	if !oneofPickPresent {
		err := WithOneofValidationError{
			field:  "Pick",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return WithOneofMultiError(errors)
	}

	return nil
}

// WithOneofMultiError is an error wrapping multiple validation errors returned
// by WithOneof.ValidateAll() if the designated constraints aren't met.
type WithOneofMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WithOneofMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WithOneofMultiError) AllErrors() []error { return m }

// WithOneofValidationError is the validation error returned by
// WithOneof.Validate if the designated constraints aren't met.
type WithOneofValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WithOneofValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WithOneofValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WithOneofValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WithOneofValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WithOneofValidationError) ErrorName() string { return "WithOneofValidationError" }

// Error satisfies the builtin error interface
func (e WithOneofValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWithOneof.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WithOneofValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WithOneofValidationError{}
